### ISSUE TITLE
Enhancement: Use hashes instead of serializing as JSON

### ISSUE THREAD

**Issue by neildaniels** [bnomei/kirby3-redis-cachedriver#2]
Instead of serializing the entire Value as JSON, it would probably be more performant and compact to simply store sore the value and expiration as a Hash.

**Comment by bnomei** [comment]
i did stick with the default kirby serialization because it works well and i can be sure it has no sideffects. since using redis already skips the read of a file i consider this a major performance boost and optimizing the data structure a minor one. afaik json is very fast in php for simple/flat arrays (which i expect most cached values to be) so i am not convinced using anything else will gain much. using json has the benefit that most objects in kirbys core know how to serialize themselfs to arrays.
https://developpaper.com/serialization-and-json-performance-evaluation/
